version: '3.8'

services:
  music-db:
    image: postgres:16
    container_name: music-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: musicdb
    ports:
      - "5434:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped

  music-catalogue:
    build: .
    container_name: music-catalogue
    environment:
      DB_URL: jdbc:postgresql://music-db:5432/musicdb
      DB_USERNAME: user
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - music-db
    restart: unless-stopped