FROM maven:3.8.6-eclipse-temurin-11 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests


FROM tomcat:9.0-jdk11
#RUN rm -rf /usr/local/tomcat/webapps/*
COPY --from=build /app/target/musicCatalogue.war /usr/local/tomcat/webapps/musicCatalogue.war
EXPOSE 8080
CMD ["catalina.sh", "run"]
